### ISSUE TITLE
Line between terrain tile

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cesium-o3de#23]
Currently there is a white line between terrain tiles. It's more noticeable when the camera is far away from the terrain
I suspect it's related to the same issue as Unreal's MSAA on mobile (https://github.com/CesiumGS/cesium-unreal/issues/468)

![image (1)](https://user-images.githubusercontent.com/20376598/153648471-fc1f055e-a7a8-4bf0-ba16-87af82b348e9.png)

**Comment by lilleyse** [comment]
Here's a closer up view of a tileset with the same problem:

![tilegaps (1)](https://user-images.githubusercontent.com/915398/163416913-ba2aa61b-7de1-4961-9880-dfb06e2aaed0.png)
