### ISSUE TITLE
Improving the Quickstart user experience

### ISSUE THREAD

**Issue by argallegos** [CesiumGS/cesium-o3de#3]
As I am drafting up the quickstart tutorial for O3DE, I'm noticing that there are quite a lot of steps. It would be great if we could condense them a little, but I'm not sure what's possible with the engine. 

Here are the current steps involved in this getting started tutorial. As far as I know, they are all necessary or else highly recommended to be able to visualize terrain in the engine. Would be great to discuss what we might be able to pare down. 

### Step 1: Install the gem
This is the same as the developer setup on the readme of this repo. We could potentially exclude it from the Quickstart.
1. Clone the repo
2. Navigate to the External folder
3. Create a new folder called Build
4. Use CMake to build Cesium Native
5. Open the System Properties panel
6. Click on Environment Variables
7. Create a new User Variable with the filepath to your local cloned directory

### Step 2: Create your project and add the gem
1. Open the O3DE Project Manager
2. Click the New Project… button and select Create New Project
3. Name your project
4. Click the Configure Gems button
5. Click the hamburger menu and select Add Existing Gem
6. Navigate to the directory you previously cloned
7. In the Gem Catalog, scroll down or search for the Cesium gem and enable it
8. Click Create Project
9. Rebuild project
10. Open project
11. Wait for the Asset Processor to finish

### Step 3: Connect to Cesium ion

1. Click the Cesium icon
2. Click the connect to Cesium ion button
3. Log in to Cesium ion

### Step 4: Set up your level

1. Create a new level
2. Hide or delete the “Ground” from the Atom Default Environment.
3. Click on the Level entity in the entity outliner. Add component - level coordinate transform
4. Right click on the level in the entity outliner, create a new entity
5. With the new entity selected, click on the quick add georeference component button in the cesium ion panel
6. Click on the new georeference. Change “Origin Type” dropdown from Cartesian to Cartographic.
7. Add the following coordinates: 
Longitude: -105.25737
Latitude: 39.736401
Height: 2250.0
(This sets the georeference location to the same as the default in Cesium for Unreal)
11. Click the “Set as level georeference button”
12. Right click on the level in the entity outliner, create a new entity
13. With the new entity selected, click on the quick add CWT+bing in the Cesium ion panel. You will now see Cesium World Terrain. 

### Step 5: Adjust your camera
These steps are not necessary to visualize a tileset, but are still part of the quickstart so that users can learn the nuances of the interface. 

1. Select the Camera object in the Entity Outliner
2. Set move speed to 100 (this is apparently the max)
3. Change the far clip distance to 100000000.0 m
4. Click “Be this camera”
5. Move around with WASD. Hold down the left shift key to move faster.

Where can we speed up this process? Some ideas:

- Installation
   - Can we make builds of the gem so that users don't have to clone the repo, build Cesium Native, etc and the user can just download a zip?
   - Is there a way to avoid adding an environment variable?
   - Can we use the "Gem Repos" system?
- Plugin functionality (please advise on whether or not these would be possible to do, I don't know so I'm just spitballing.)
   - Is there any way to add a Level Coordinate Transform automatically to the level entity? Maybe the first time we add something from the cesium panel, we could check to see if it exists, and if not, add it. As far as I know, every level with a cesium tileset will need it to work, so we should try to add it automatically.
   - Can we automatically delete the default ground plane? I think that would just save time, and I doubt many users will need it, plus it gets in the way of viewing the tilesets if you haven't figured out how to move the editor camera.
   - Can we have georeferences start with Cartographic coordinates by default, and include a default longitude/latitude/height? Otherwise, this adds more steps before users can visualize a tileset. Also, it makes it more in line with the Cesium for Unreal workflow, and teaches you how to view terrain without adding a location-specific tileset.
   - Can we automatically tweak camera settings, such as adjusting the move speed and changing the far clip distance? Those are settings that all users will likely want in order to see their tilesets. 
- Perhaps for all the plugin functionality steps we could add a button like "Use suggested level setup" that users could just press that would make all those changes automatically. This would significantly speed up the process. Is that something that would be possible?

**Comment by baothientran** [comment]
Below is the plan to automate some of the steps:

For step 1 install the gem: 1->4 can be automated by downloading the binary from github CI similar to Unreal
For step 2: that's probably needed
For step 3: same as step 2
For step 4 Set up level:
- cleaning up the unneeded entities (ground, shader ball etc) is probably needed by user.
- Level georeference is replaced by Origin Shift, which I think I can automate it, so user doesn't need to add it to the level.
- Add default value for Origin Shift
- I can create an entity along with 3D Tiles component too, so the step for right clicking and add new entity probably isn't needed

**Comment by baothientran** [comment]
@argallegos I think some of the improvement suggested above are in main now

**Comment by baothientran** [comment]
For step 4, it should be just one step now by adding CWT and that's it.
For step 5, user only needs to adjust editor camera speed. Camera far clip is set to be very high by default
The plus button in quick-add will automatically create new entity, so right click and manually add a new entity is not longer needed
